### ISSUE TITLE
use compression for static files

### ISSUE THREAD

**Issue by kepta** [willemarcel/osmcha-django#100]
Currently all the static files are served without any compression.
It would really great to have the `osmcha-django` serve them with the `gzip encoding`.

This would give us 
`757KB` to `212.68 KB` for the main.js file, which will shave off 4seconds approximately in the loading. 

cc @willemarcel @batpad

**Comment by willemarcel** [comment]
Done in https://github.com/willemarcel/osmcha-django/commit/fb33093758d0bc5bf87944e2eb76a02b89aaaa78
