### ISSUE TITLE
Keeping labels fresh and up to date

### ISSUE THREAD

**Issue by bkowshik** [willemarcel/osmcha-django#104]
The following changeset has a 👎 on osmcha, looks like the highway had a `oneway=no` which got modified into `oneway=yes`.

- https://osmcha.mapbox.com/changesets/47392777

About a month later, another user comes along and modifies back the `oneway=yes` to `oneway=no` in the changeset [48628369](https://osmcha.mapbox.com/changesets/48628369) with the following changeset comment.

> Adjusting for accuracy. Resident of area.

From https://osmlab.github.io/osm-deep-history/#/way/6052634

![modification](https://user-images.githubusercontent.com/2899501/27403911-e3c07e04-56e9-11e7-97c4-290b33bf76f3.gif)

This is amazing right? So, in this case it looks like the right thing to do is to modify the label on osmcha from 👎 to 👍 What would a good workflow be to keep the labels fresh and up to date?

---

cc: @srividyacb

**Comment by willemarcel** [comment]
Right now, only the user that checked the changeset can uncheck it and check again with the correct label. But I just sent a commit to allow staff users to uncheck changesets checked by any user: https://github.com/willemarcel/osmcha-django/pull/103/commits/fb751cc85986919c03caab074606028cc81861a9

I believe it will be deployed today yet.
