### ISSUE TITLE
Different API results

### ISSUE THREAD

**Issue by kepta** [willemarcel/osmcha-django#105]
### Brief
When I query 
https://osmcha.mapbox.com/api/v1/changesets/?page=1&page_size=75&all_reasons=36,44

gives result count = 1

Is **totally** different from 

https://osmcha-django-staging.tilestream.net/api/v1/changesets/?page=1&page_size=75&all_reasons=36,44
which gives result count > 2lk

Now, if you look at changeset iD [49744659](https://osmcha-django-staging.tilestream.net/changesets/49744659) which has the reasons
`New mapper`, `Invalid tag modification`. It exists both on [production](https://osmcha.mapbox.com/changesets/49744659), [staging](https://osmcha-django-staging.tilestream.net/changesets/49744659)

### Steps

search on `production` with the filter 

https://osmcha.mapbox.com/api/v1/changesets/?page=1&page_size=75&all_reasons=36,44 

**Expected** Should see the changeset  49744659
**Actual**  I dont.

**Comment by kepta** [comment]
cc @willemarcel and @batpad

**Comment by willemarcel** [comment]
@kepta On `production` the ids 36 and 44 are not of `New mapper, Invalid tag modification` reasons: https://osmcha.mapbox.com/api/v1/suspicion-reasons/

**Comment by kepta** [comment]
Thanks @willemarcel was confused
