### ISSUE TITLE
decoding URI component

### ISSUE THREAD

**Issue by kepta** [willemarcel/osmcha-django#107]
the front end is encoding the filters params to allow things like 
`comment=#HOT` to `comment=%23HOT`.

^^ This works.

But if I make the following request for sorting by created object.

https://osmcha.mapbox.com/api/v1/changesets/?page_size=75&page=1&date__gte=2017-06-20&checked=True&order_by=%2Bcreate

Notice `order_by=%2Bcreate`. It doesn't work.

@willemarcel The above url is equal to this.
https://osmcha.mapbox.com/api/v1/changesets/?page_size=75&page=1&date__gte=2017-06-20&checked=True&order_by=+create

Which gives correct output.

@willemarcel what do you think?

**Comment by willemarcel** [comment]
@kepta the correct code for `-` is `%2D`

:D

**Comment by kepta** [comment]
@willemarcel I was talking about `+`,  does it work with `-`?

**Comment by willemarcel** [comment]
@kepta no, the options are `create` and `-create`, the same to the other order params.

**Comment by kepta** [comment]
oh my bad, I assumed it to be `+`.
