### ISSUE TITLE
Inconsistent AOI results

### ISSUE THREAD

**Issue by kepta** [willemarcel/osmcha-django#108]
AOI results are not the same as a query with the same filters.

AOI: https://osmcha.mapbox.com/api/v1/aoi/e3a21728-1b2d-4ee4-ae4a-de5cabe2bdba/
Returns 
```
{
  checked: "False",
  in_bbox: "-49.0094,-20.2281,-34.4958,-6.1367",
  is_suspect : "True"
}
```
If I query for changesets : https://osmcha.mapbox.com/api/v1/aoi/e3a21728-1b2d-4ee4-ae4a-de5cabe2bdba/changesets/?page_size=75&page=1
I get a count of `943911`.

However if I apply the same filters: https://osmcha.mapbox.com/api/v1/changesets/?page_size=75&page=1&is_suspect=True&checked=False&in_bbox=-49.0094%2C-20.2281%2C-34.4958%2C-6.1367
I get a count of `4839 `.

From what I understand about AOIs, they are a way to save filters. @willemarcel am I doing something wrong?

Stack: `production`

**Comment by willemarcel** [comment]
Hi @kepta 

The `in_bbox` filter was not working... a bad written test gave me the impression that it was working. Thanks for finding that bug!

I fixed it and released the version [2.1.0](https://github.com/willemarcel/osmcha-django/tree/v2.1.0). Can @amishas157 deploy it?
