### ISSUE TITLE
Get all AOIs gives inconsistent results

### ISSUE THREAD

**Issue by kepta** [willemarcel/osmcha-django#109]
Randomly the AOI https://osmcha-django-staging.tilestream.net/api/v1/aoi/ api would give less results. 

I have attached a screen recording. Note the array is length in 1 in between.

![out](https://user-images.githubusercontent.com/6966254/28110625-9c7f3c10-6710-11e7-8bac-71edbe808592.gif)

This happens in the production stack as well.

**Comment by willemarcel** [comment]
I couldn't understand the problem with your recording... I tried to reproduce it in the staging API and sometimes it returned a `FeatureCollection` with zero itens. It happens one time in each 5 requests approximately. In my machine this error didn't occurred.

I realized that it would be good to have a `creation date` field in the AoI, so we could order by date to show to the user. What do you think? We could give the option to order by name or date.

**Comment by willemarcel** [comment]
It seems it was caused by the partial implementation of cache in the servers. I disabled the cache until I can install redis on the AWS server.

@kepta could you test if it's working properly now?
