### ISSUE TITLE
Add link to open changeset in JOSM

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#11]
It would be useful to have a button that opens the changeset in JOSM for a user to review it better.

@willemarcel if you agree to this, I'm happy to work on this.

**Comment by willemarcel** [comment]
Yes, @batpad, you can work on it! I have already thought about this feature, and it would be very useful!

**Comment by willemarcel** [comment]
One thing we could improve is to prevent the link to open another window. Maybe one good way of doing this is open a bootstrap modal.

**Comment by batpad** [comment]
Hm, @willemarcel the link should not open in another window right now - the HTML is like that only as fall-back in case the user does not have Javascript enabled. If the user has Javascript, it should just automatically open in JOSM (do you think we should have a modal there just informing the user that the action was successful?).

Let me know what you think - either way, this should be fairly straightforward to implement.

**Comment by batpad** [comment]
@willemarcel the javascript was not working because jQuery was no longer on the page. I have fixed this in https://github.com/willemarcel/osmcha-django/pull/15 . Let me know if that looks okay and seems to be the desired behaviour?

The button and layout looks great, btw!

**Comment by willemarcel** [comment]
I forgot to check... It's great now! Thank you!
