### ISSUE TITLE
Add total and flagged changesets count to stats end point

### ISSUE THREAD

**Issue by geohacker** [willemarcel/osmcha-django#111]
Can we add total changesets that matches the filter and flagged changesets per reason to the stats end point? Thank you!

cc @willemarcel @batpad

**Comment by geohacker** [comment]
Right now: http://osmcha.mapbox.com/api/v1/stats/?date__gte=2017-07-13&format=json
This will show checked changesets, and number of harmful changesets out of the checked. But we don't know what the backlog is.

**Comment by willemarcel** [comment]
Solved with https://github.com/willemarcel/osmcha-django/commit/6233a7202b768a26e11ebcf22cbbb6be2ac9e20a
