### ISSUE TITLE
RSS feed for an AOI

### ISSUE THREAD

**Issue by geohacker** [willemarcel/osmcha-django#116]
Could we provide an RSS feed for an AOI? 
@batpad @willemarcel

**Comment by batpad** [comment]
Yes! I think this would be great and I think definitely on the roadmap.

@willemarcel no rush at all on this, but do you think this is something that you can start sketching out how it might look?

**Comment by willemarcel** [comment]
Yes! It'll be great to have it!

**Comment by willemarcel** [comment]
Solved with https://github.com/willemarcel/osmcha-django/commit/e52a9ae7c70e0e526896162575e3261bc941735a
