### ISSUE TITLE
Filter changesets by blacklisted users list

### ISSUE THREAD

**Issue by amishas157** [willemarcel/osmcha-django#119]
It will be super useful to have changeset filtering by blacklisted users.

cc @willemarcel

**Comment by willemarcel** [comment]
Right now you can access the `/blacklisted-users/` endpoint to get the `uids` of the `BlacklistedUsers` and use it to filter the changesets. As only the staff users can add, get and remove blacklisted users, I'm not sure if it would be good to add a explicit filter to blacklisted users.

opinions, @batpad ?

**Comment by willemarcel** [comment]
@amishas157 closing this for now. If you need this filter in the future, reopen please! ;)

**Comment by amishas157** [comment]
Sounds good @willemarcel
