### ISSUE TITLE
Add an endpoint to filters features whose changesets have been checked/unchecked

### ISSUE THREAD

**Issue by amishas157** [willemarcel/osmcha-django#120]
Filing this issue per chat with @willemarcel

**Comment by willemarcel** [comment]
added on https://github.com/willemarcel/osmcha-django/commit/ed19b69657379033de835367460244792d6d77a3

**Comment by willemarcel** [comment]
It's already on production!

**Comment by amishas157** [comment]
Thanks @willemarcel 🤘
