### ISSUE TITLE
Post reviews and tags as changeset discussions

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#128]
Related to discussion here: https://github.com/openstreetmap/iD/issues/4133#issuecomment-326495697

I feel that the changeset page on osm.org should ideally be the canonical place for information about a changeset.

I propose:

Every time a reviewer reviews a changeset on OSMCha, we post a message to the changeset as a discussion item, for example:

`This changeset was flagged "thumbs down" on OSMCha(link) by <user>`
`<User> added the "Intentional Vandalism" tag on OSMCha`
`<User> added the "Fixed" tag on OSMCha`

I'm not sure if there's any policy around bots posting changeset discussions, but I think this would really help follow a pattern of having information from any number of review tools feed back to osm.org.

@willemarcel I think this might have come up / been discussed before? What do you think?

cc @planemad for thoughts and to cc more folks you think maybe relevant to this discussion about discussions.

**Comment by HolgerJeromin** [comment]
Thanks for this discussion. changeset discussions are probably the only way right now for this.

I would like to have not only prose text, but also something QA tool agnostic machine readable. 
Hash tags are probably the way to go
`#reviewstate:<username>=noProblems`
`#reviewstate:<username>=problemsFound`
`#reviewstate:<username>=problemsFixed`

depending on the QA software the changeset can be hidden if one or more (depending on a preference)  users had marked the changeset as noProblem/problemsFixed

**Comment by batpad** [comment]
> Hash tags are probably the way to go

Something that is easily machine readable, but also doesn't make the changeset discussions look like some strange non-understandable machine-speak would be great :-) - I have no objections to the rough syntax you have proposed, but if we do want to arrive at a rough consensus of a shared syntax of how reviews are communicated back to changeset discussions in a machine-readable way, let's try and get some more opinions and perhaps some refinement of possible syntax. Will try and spend some time thinking about this as well :-)

Thanks so much for the inputs @HolgerJeromin !

**Comment by HolgerJeromin** [comment]
Making this kind of readable is a good idea, especially as the review are probably requested by non so techy people.

Scanning [QA wiki page](https://wiki.openstreetmap.org/wiki/Quality_assurance) i found only "osm-suspicious" which could use this. Did i overlooked a tool? :)

**Comment by willemarcel** [comment]
@batpad I've thought about this some time ago... Yes, we need to check the bot policy for OSM changesets.

One thing that I see as a potential problem is that every time a changeset comment is made, the user will receive an email. This can bother some users and make them don't give attention to more relevant changeset emails...

**Comment by planemad** [comment]
👍 for delivering the feedback to the OSM changeset. This can really boost social activity on the map and make new users feel more confident to make edits.

> This can bother some users and make them don't give attention to more relevant changeset emails...

Having a personalized message from the reviewer with feedback along with the automated review will make such messages a lot more useful and not feel like noise. Eg.


>Nice work, thank you for updating this area!
_Your edit was reviewed using [OSMCha](https://osmcha.mapbox.com/changesets/51737517) and has helped make a better map 👍_

>Thank you for mapping the stream, but it looks like you have added the coordinates as tags from some GPS converter you used. This is unnecessary and can be removed. Happy to help if you are having trouble mapping or want more feedback. 
_Your edit was reviewed using [OSMCha](https://osmcha.mapbox.com/changesets/51730588) and had some issues. Please reach out for assistance to fix your edits or read the the [documentation](https://wiki.openstreetmap.org/) if you are new to mapping._

**Comment by willemarcel** [comment]
A related comment: https://github.com/mapbox/osmcha-frontend/issues/113#issuecomment-328347099
It talks about to request the user that reviewed a changeset to reconsider his review. I think we could implement this right now.

I've checked the [API policy](https://operations.osmfoundation.org/policies/api/) and I think it's ok to use the API to add comments on the changeset.

**Comment by joostschouppe** [comment]
This would be extremely useful, especially given that people use both Pascal's tool and osmcha to review the review_requested changesets. It doesn't necesarily need to be machine readible. In Pascal's tool, the number of comments is easily visible. So one can prioritize uncommented changesets.

I really like @planemad 's suggestion. I would like osmcha to prompt me automatically with this "personal message" upon completing my review. The message could be assembled using the extra tags as well. The last part of the message could be permanently fixed, so that e.g. the link can be used for automated reading in another application.

**Comment by pa5cal** [comment]
As already explained by @joostschouppe, the review comment doesn't need to be machine readable. IMHO the most important thing is that the reviewed changeset gets a changeset comment. Furthermore, it would be good when it contains maybe some kind of "personalized message from the reviewer" (as proposed by @planemad). Also, the reviewer (OSM contributor) should create the comment and not some kind of OSMchaBot.

**Comment by willemarcel** [comment]
This feature is now deployed on production. If you have some feedback about it, let me know! Thanks!!!
