### ISSUE TITLE
[Question] Do we need angular.js?

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#13]
@willemarcel I notice that angular.js is being referenced in `base.html` here: https://github.com/willemarcel/osmcha-django/blob/master/osmchadjango/templates/base.html#L30

Is it being used anywhere? Do we see a use case for Angular? It seems like the javascript for this should be pretty simple and just some jQuery should be okay? Just wasn't sure if the idea was to use Angular for something and I should keep that in mind if I land up writing any JS.

Thank you.

**Comment by willemarcel** [comment]
It's more one of the things I forgot to remove from the project template I used. I think we can remove it now.

**Comment by willemarcel** [comment]
I removed the angular js lib in https://github.com/willemarcel/osmcha-django/commit/e70f1c62e9e5f1ff6952474a8c93632ea1c172cc
