### ISSUE TITLE
Links with & get truncated when posting changeset comments

### ISSUE THREAD

**Issue by Nakaner** [willemarcel/osmcha-django#158]
It is sometimes not possible to post changeset comments which contain an URL in the middle which contains the `&` character (query string argument seperator). OSMCha responds "failed to comment" (or something like that)

If I put the link at the end of the text, the link is truncated at the `&` character (`&` is missing, too).

**Comment by willemarcel** [comment]
Thanks for the report, @Nakaner ! Sometime ago I fixed some problems with special characters, but have never noticed the `&` case. I'll work on that issue soon.

**Comment by willemarcel** [comment]
Fixed with https://github.com/willemarcel/osmcha-django/commit/e1a3349449073f0caed91bfcb56d5b9fe30b6c95

We will deploy it to production soon.
