### ISSUE TITLE
Documentation to install grunt

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#18]
@willemarcel following the documentation in the `README`, I was not able to get the command `grunt serve` to work.

To get the `grunt` command on the CLI, I needed to do `npm install -g grunt-cli` as per http://gruntjs.com/getting-started#installing-the-cli

Also relevant: http://stackoverflow.com/a/18877352

I am using Mac OSX `El Capitan`. If this issue is specific only to Mac OSX, please feel free to close. However, I remember having the same issue on linux for a different project.

Thank you :)

**Comment by willemarcel** [comment]
Grunt is not used any more! :D
