### ISSUE TITLE
Documentation for running rabbitmq + celery and importing changesets

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#2]
Firstly, thank you for a wonderful project!

Found the documentation a little lacking in how to actually import changesets, etc. This is what I landed up doing (on a Mac OS X):

```
brew install rabbitmq
rabbitmq-server

pip install celery
celery -A config worker -l info

python manage.py shell
from osmchadjango.changeset.tasks import import_replications
import_replications(1525500, 1525536)
```

Not sure if there is meant to be a better way, and rabbitmq / celery probably needs a bit of documentation on deploying to production, etc. - but this worked super well! I would be super happy to help out / contribute to this @willemarcel , please let me know if I can help with this. Thank you again for an excellent project!

**Comment by willemarcel** [comment]
Great! Thank you! I'll put it in production on the next days!

To put celery in production we need a celery service and celery beat running on the machine https://celery.readthedocs.org/en/latest/tutorials/daemonizing.html#daemonizing

and we need to set periodic tasks to import changesets daily or hourly https://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html

I think I'll write a model to register the last replication file imported, so we didn't lose control of what we imported. I'll open some issues and you can can solve some. Thank you!

**Comment by batpad** [comment]
Thanks for the response @willemarcel !

The periodic task and model to register last replication imported sounds perfect and would neatly wrap up the import process, I think.

I will see if I can get some time on the other issues you have filed this week. Hope to be in touch - let me know if it helps to find a time to chat about this at some point - hope I am able to help with this.

**Comment by bkowshik** [comment]
@batpad thank you for the amazing documentation [^](https://github.com/willemarcel/osmcha-django/issues/2#issue-110283090) 👏 This is amazing and has to be part of the `README.md` as soon as possible.

@willemarcel @batpad can you list down next actions here to get this merged to `master`?

---

cc: @geohacker
