### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by willemarcel** [willemarcel/osmcha-django#23]
- [ ] Adjust the footer (I tried to do this, but the project is configured with sass css compilation. I think we should remove sass)
- [x] Add a link to github
- [x] Add a description of the project in the "About" page.

**Comment by alexandre-mbm** [comment]
@willemarcel, begin each line like a list item: `- [ ]`

**Comment by willemarcel** [comment]
@alexandre-mbm thanks again!

**Comment by alexandre-mbm** [comment]
Okay. You may to erase this and your comment now.
