### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by naoliv** [willemarcel/osmcha-django#29]
We need to have some kind of comment system for the changesets.
This should also allow to discuss and coordinate possible reverts or other actions (for example, somebody say "I am working on this" and avoid duplicated work and conflicts)

**Comment by batpad** [comment]
Do we need a separate commenting system inside osmcha-django, or do you think we can use existing changeset discussion in OSM for this, and find some way to show the discussions on the changeset detail page?

It makes sense to me to have a single place where discussions on changesets happen, and that would ideally be on OSM. If this makes sense, I can work on integrating changeset discussions from OSM onto the changeset detail page.

**Comment by naoliv** [comment]
The comments would be used for the review process itself.
I don't think that `This changesets really looks suspicious for me. Could somebody else review it and confirm this?` fits in the changeset discussion, for example.

**Comment by alexandre-mbm** [comment]
Hint: tooltip regarding the scope of the comment here in osmcha.

**Comment by willemarcel** [comment]
I like the idea of @naoliv, although I think it is not crucial for now.

**Comment by danstowell** [comment]
IMHO it'd be better to keep discussion in the existing OSM changeset comment thread. OSMCHA currently renders the changeset discussion, which is good, and it's just one click to go over to OSM and join that conversation. I'd vote to close this issue FWIW

**Comment by willemarcel** [comment]
It was implemented by @batpad! Thank you!
