### ISSUE TITLE
Login with OSM OAuth

### ISSUE THREAD

**Issue by willemarcel** [willemarcel/osmcha-django#3]
Implement login with OSM OAuth https://wiki.openstreetmap.org/wiki/OAuth

**Comment by batpad** [comment]
hey @willemarcel sorry did not get time on this last week. I will work on this this week, as well as the "mark verified" feature. Shall update progress here.

**Comment by willemarcel** [comment]
hi, @batpad 

Maybe this can help us on this issue: https://github.com/umap-project/umap/blob/master/umap/osm_backend.py

**Comment by batpad** [comment]
hey @willemarcel - I was looking at https://pypi.python.org/pypi/python-social-auth - it has a back-end for OSM and a sample Django implementation.

It may require changing around the User model a little bit. Do you think the app should only allow login via OSM, or also have its own login system? I think only allowing login via OSM should be okay?

Let me know if you think it's okay to change around the User model a bit according to the python-social-auth examples and I can try and hack something up :) - thanks!

**Comment by alexandre-mbm** [comment]
>  I think only allowing login via OSM should be okay?

:+1:

**Comment by willemarcel** [comment]
Yes, login only by OSM Auth is OK!

**Comment by alexandre-mbm** [comment]
I do not known as it can help you, or if it is good in really, but I found the project [python-social-auth] yesterday, from a fast view of [openstreetmap.py].

[python-social-auth]: /omab/python-social-auth
[openstreetmap.py]: /omab/python-social-auth/social/backends/openstreetmap.py

**Comment by willemarcel** [comment]
Issue solved.
