### ISSUE TITLE
Allow reviewers to "white-list" users

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#30]
As per discussions in #14, we decided that it would be a good idea to allow each reviewer to maintain their own personal white-list of users.

What would this mean?

A reviewer (who is just anyone using osmcha-django to monitor changesets) can chose to `white-list` a particular user. Once that user is white-listed, their changesets will no longer show up in the list of changesets for that reviewer. (They will continue to show up for everyone else).

@willemarcel I have started sketching this out here: https://github.com/batpad/osmcha-django/tree/whitelist-users . I have an implementation that "works", but needs more work before I can make a PR.

Please let me know if the general approach looks okay to you, and then I can:
- [ ] Improve UI to use modals and not `alert` and `confirm` boxes.
- [ ] Write tests.
- [ ] Add list of white-listed users to user profile page with extra management options there.

... Anything else you think needs to be fixed before this can be merged.

**Comment by alexandre-mbm** [comment]
And reviewers with bad intent?

**Comment by batpad** [comment]
@alexandre-mbm sorry, not sure what your question is here?

A reviewer with bad intent can't do any harm since if they white-list a user, that user disappears only for them and not for anyone else.

If you meant 'what to do about users with bad intent', I'm not sure if you mean creating some sort of `black-list` to flag bad users, who have made harmful changesets. I think this maybe a good idea, but not sure how this feature would work exactly. Could you open a separate ticket for that if you think it is required, and how you think it should work?

Thank you.

**Comment by willemarcel** [comment]
Hi @batpad 

Yeah! Your implementation looks great!

**Comment by batpad** [comment]
@willemarcel would appreciate your help on this function: https://github.com/batpad/osmcha-django/commit/9dad1f8cce85696f181780665d2cadb0756568e4#diff-dc9f57b89675fd275bc9ddb5f120e2f3R88 . It would be maybe nice to make it a Class-Based View to follow the same pattern as the other views? Am just not sure of the best way to do that in this case. Or if you think it's fine as it is, let me know. Thanks!

One thing that I will fix is:

 - [ ] Remove `csrf_exempt` decorator and handle sending `csrf` token from front-end.

**Comment by willemarcel** [comment]
You should follow the model used on SetHarmfulChangeset and SetGoodChangeset views (https://github.com/willemarcel/osmcha-django/blob/master/osmchadjango/changeset/views.py#L25). I don't see as a big problem to use function based views, but the code of CBV is also very simple.

In that case, I think it's not necessary to have a method GET and a confirmation page, but it would be good to have another view to delete a UserWhiteList

**Comment by alexandre-mbm** [comment]
@batpad 

> A reviewer with bad intent can't do any harm since if they white-list a user, that user disappears only for them and not for anyone else.

Sorry. I had not realized so. I thought the white-list marking the changesets.

**Comment by willemarcel** [comment]
closing, @batpad! You implemented the whitelist! Thank you!
