### ISSUE TITLE
Modify classification of changesets

### ISSUE THREAD

**Issue by willemarcel** [willemarcel/osmcha-django#31]
Verifying some changesets, I observed a new category of changesets. Some changesets contain some errors, but are not totally harmful. The correct definition would be "good but with errors".

Example: http://osmcha.openstreetmap.com.br/36851849/

The user mapped some new roads, but added a wrong classification, forgot to map a bridge and didn't connect with the main road. I set it as harmful because I had to fix the changeset.

Maybe the problem is the term "harmful" and we should change it for some word less severe.

Another option would be to change the field harmful for a CharField with three options: "harmful", "good" and "some_errors" (or another better term).

**Comment by alexandre-mbm** [comment]
I suggest a combobox for consistence. And comments (another issue).
