### ISSUE TITLE
Undo verification of a changeset

### ISSUE THREAD

**Issue by maning** [willemarcel/osmcha-django#32]
Add an option to undo verification status.  This is useful because the reviewer might have made a mistake or another person reviewed the changeset and thinks otherwise.
A future enhancement might be a scoring mechanism, so more people can confirm the changeset edit.

For now, undo function would be super useful.

**Comment by willemarcel** [comment]
Yes, @maning. I have had some situations when I needed to undo the verification

**Comment by willemarcel** [comment]
Solved with the new version
