### ISSUE TITLE
Have an icon (or other graphical element) indicating that the changeset has comments

### ISSUE THREAD

**Issue by naoliv** [willemarcel/osmcha-django#33]
We could have some kind of icon/text/something else when a changeset has comments in OSM.

For example, in http://osmcha.openstreetmap.com.br/36930068/ we should be able to see that in http://www.openstreetmap.org/changeset/36930068 there is one comment, without needing to open the changeset.

Maybe even directly displaying the comments inside osmcha, with some text saying "This changeset has X comments. Click to view."

**Comment by geohacker** [comment]
@naoliv great idea! We'll make this happen.

**Comment by batpad** [comment]
This is now implemented - a changeset should show all the comments on the changeset page :-)
