### ISSUE TITLE
broken link: Users with harmful changesets

### ISSUE THREAD

**Issue by Locke** [willemarcel/osmcha-django#43]
When I visit http://osmcha.mapbox.com/all-blacklist-users and click on a user name I land on  http://osmcha.mapbox.com/?user=XYZ and see everything, not only changesets from this user. I think the url should point to http://osmcha.mapbox.com/?usernames=XYZ&is_suspect=False

**Comment by batpad** [comment]
Oops. Thanks so much for the report @Locke - should be fixed soon :-)

**Comment by batpad** [comment]
This should be fixed now. Thanks again @Locke !

**Comment by Locke** [comment]
Thanks for the fast fix. I think it should show all changesets, not only suspicious ones, but that's up to you.
