### ISSUE TITLE
visual bbox selector (for filter) should show where current bbox is

### ISSUE THREAD

**Issue by danstowell** [willemarcel/osmcha-django#45]
When you look at some query results, and go back into "Show Filters > Bbox > Map", the current bbox (if any) should be already on the map, rather than starting back at square one. Otherwise it's hard to visually determine what the current bbox actually refers to.

**Comment by batpad** [comment]
Thanks for the report @danstowell . This should now be fixed using: https://github.com/batpad/osmcha-django/commit/e0296ee16a5b4baaf69cf10c77c5fb17a8032677

(just to note we currently use the above fork for the deploy on osmcha.mapbox.com but we are going to be working on merging all the code upstream to this repository in the next month.)
