### ISSUE TITLE
False-positives occurring for "edited a wikipedia"

### ISSUE THREAD

**Issue by danstowell** [willemarcel/osmcha-django#46]
[This example](https://osmcha.mapbox.com/44724329/) is not the first time I've seen an item labelled as "edited a wikipedia" yet I don't think the "wikipedia" tag changed at all. Why does this false-positive detection show up?

**Comment by batpad** [comment]
The `reasons` in the features listing need better explanations. `Edited a wikipedia` is simply flagging ANY changes to things with a `wikipedia` tag. But the little explanation reasons can be confusing. We should create an explanation for each reason so that it's clear what's going on.
