### ISSUE TITLE
Changeset discussions are listed but not in temporal order

### ISSUE THREAD

**Issue by danstowell** [willemarcel/osmcha-django#47]
[Example here](https://osmcha.mapbox.com/43749373/) - a conversation of 13 messages, but OSMCHA doesn't render them in temporal order... so it's impossible to comprehend the conversation...

**Comment by batpad** [comment]
Oops. Thanks so much for the catch @danstowell .

**Comment by batpad** [comment]
This was a bug in `osm-comments-api` that we use to fetch the changeset comments.

I have fixed it here: https://github.com/mapbox/osm-comments-api/commit/0e0def076e86dae8382f912663e8c5573e28af3c and made a new deploy of the API. Changeset comments should now be listed in temporal order.

It is probably useful to also display the timestamp of a comment. Will work on that. Thanks again for the catch, @danstowell .

**Comment by danstowell** [comment]
and thanks for the fix!
