### ISSUE TITLE
[premerge] Automate test runs / setup CI

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#49]
This probably involves a few things to improve the current basic tests in place:

 - Flake8 / PEP8 lint checks
 - Create test fixtures to load test db with
 - Ensure tests for models and filters
 - Develop pattern for testing API end-points

^ Ensure all this works with something like `python manage.py test` and then ensure integration with an online CI tool like Circle or Travis.

cc @willemarcel

**Comment by willemarcel** [comment]
@batpad I configured `travis-ci` and `coveralls`. Coveralls is not working yet because it needs all the test pass to count the test code coverage. I'll check the failing tests and then make tests for the other parts of the code
