### ISSUE TITLE
python-social-auth missing from requirements

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#5]
Trying a fresh setup following the documentation:

- Checked out code
- Created virtualenv
- Ran `pip install -r requirements/local.txt`

Then tried `python manage.py migrate`

And I get the error:
`ImportError: No module named social.apps.django_app.urls`

This is fixed after running `pip install python-social-auth` . Perhaps just need to add it to requirements/base.txt?

**Comment by willemarcel** [comment]
fixed in https://github.com/willemarcel/osmcha-django/commit/3c07799a9a914e50faf05c08b993bd62c81a771c

thank you!
