### ISSUE TITLE
[premerge] Remove weird whitelisting logic

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#50]
Right now, the logic of what user is "whitelisted" is a bit weird: https://github.com/willemarcel/osmcha-django/blob/65cc7cd5b2bb197f6f43e837f9850117f775d497/osmchadjango/changeset/views.py#L135 - if a user is on more than 2 user white-lists, the user is automatically white-listed.

While this was okay when we were testing this as a small team, it adds unneeded complexity to the SQL query and the logic is a bit "magic" and hard to explain and I think should be removed.

Let's just let users have personal white-lists for users whose changesets they want to ignore. And in the future, let's make it simple for users to share whitelists amongst themselves to make it easier for a team / group using this to white-list users as a group.

For now, let's just remove the logic that checks for the user being on multiple white-lists.

cc @willemarcel

**Comment by willemarcel** [comment]
Solved with https://github.com/willemarcel/osmcha-django/commit/2fb5fb6b02681f31af3af2fb1c00141d86219f80
