### ISSUE TITLE
[premerge][QUESTION] Why do we have `contrib/sites` ?

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#53]
@willemarcel do you know why we have https://github.com/willemarcel/osmcha-django/tree/premerge/osmchadjango/contrib ? Is this something used / needed, or can it be dropped?

**Comment by willemarcel** [comment]
This [link](https://github.com/pydanny/cookiecutter-django/blob/master/docs/faq.rst#why-is-there-a-djangocontribsites-directory-in-cookiecutter-django) explains why the `contrib.sites` exists, I think we don't need it, but I tried to remove and I had the error above, so I think we should stick with it to avoid problems in the migrations. What do you think, @batpad ?


> You have unapplied migrations; your app may not work properly until they are applied.
> Run 'python manage.py migrate' to apply them.

> Django version 1.10, using settings 'config.settings.local'
> Development server is running at http://127.0.0.1:8000/
> Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
> Quit the server with CONTROL-C.
> ^C(osmcha) [wille@sailboat osmcha-django]$ ./manage.py migrate
> Operations to perform:
>   Apply all migrations: account, admin, auth, changeset, contenttypes, feature, sessions, sites, social_auth, socialaccount, users
> Running migrations:
>   Rendering model states... DONE
>   Applying sites.0002_alter_domain_unique...Traceback (most recent call last):
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
> psycopg2.ProgrammingError: ERRO:  relação "django_site_domain_a2e37b91_uniq" já existe
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "./manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/core/management/base.py", line 305, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/core/management/base.py", line 356, in execute
>     output = self.handle(*args, **options)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 202, in handle
>     targets, plan, fake=fake, fake_initial=fake_initial
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/migrations/executor.py", line 97, in migrate
>     state = self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/migrations/executor.py", line 132, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/migrations/executor.py", line 237, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 204, in database_forwards
>     schema_editor.alter_field(from_model, from_field, to_field)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
>     old_db_params, new_db_params, strict)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 117, in _alter_field
>     new_db_params, strict,
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 678, in _alter_field
>     self.execute(self._create_unique_sql(model, [new_field.column]))
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 112, in execute
>     cursor.execute(sql, params)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
>     return super(CursorDebugWrapper, self).execute(sql, params)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/home/wille/.virtualenvs/osmcha/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
> django.db.utils.ProgrammingError: ERRO:  relation "django_site_domain_a2e37b91_uniq" already exists

**Comment by willemarcel** [comment]
Finally, `contrib.sites` is needed to setup the URL of the RSS feed.
