### ISSUE TITLE
[premerge] Add db_index where appropriate

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#54]
Now that we are using many columns and attributes to filter and search, we should check that columns are appropriately indexed.

For a start, maybe the `created`, `modified`, `deleted` integer fields and the date fields that are used frequently to search.

We should then think more about other indexes, especially for full text search. Explore using Postgres full-text search with `tsearch2` or so, but getting the basic indexes in place first would be great.

**Comment by batpad** [comment]
Oops, saw a few things there already have `db_index=True` set. I think we should add it for everything we search by, which would include `date`, `bbox`, `checked` and `harmful`. And let's make a separate ticket for integrating better full text search.

**Comment by willemarcel** [comment]
Solved with https://github.com/willemarcel/osmcha-django/commit/a66bb88d4c625393f0a554765c26c69442ed49bd
