### ISSUE TITLE
Add a description field for SuspiciousReason

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#56]
Will be nice to be able to add more details about "suspicious reasons", to be able to write exactly how a detector works and what it flags, etc. Will help clarify to someone looking exactly the logic and code used to flag something.

 - [x] Add description field to suspicious reason model
 - [x] Enable editing in Admin
 - [ ] Create a simple page which lists all `reasons` along with descriptions, with html anchors for each reason to be able to link to.

**Comment by willemarcel** [comment]
Clossing it. The first two items were implemented and the last item is tracked on https://github.com/mapbox/osmcha-frontend/issues/18
