### ISSUE TITLE
List changesets by users

### ISSUE THREAD

**Issue by willemarcel** [willemarcel/osmcha-django#6]
- [ ] Add a generic ListView that shows the changesets of each user.
- [ ] Add a link to that view in the changeset detail page

**Comment by alexandre-mbm** [comment]
Enjoy this code:
```
- [ ] Add a generic ListView that shows the changesets of each user.
- [ ] Add a link to that view in the changeset detail page
```

**Comment by willemarcel** [comment]
thanks for the tip!

**Comment by alexandre-mbm** [comment]
I erased my tip. You can erase this my comment and your thanks. Thanks.
