### ISSUE TITLE
Save Filter Settings?

### ISSUE THREAD

**Issue by DaveF63** [willemarcel/osmcha-django#66]
Hi
Is there a reason the filter query doesn't save its settings?

**Comment by willemarcel** [comment]
@DaveF63 do you mean to save a filter query to reuse it later? We will have it soon! Each user will be able to save their favourite queries.

**Comment by DaveF63** [comment]
Great. Thnaks

The numerous filter options appear quite baffling. Would it be possible to simplify them or maybe have some of the options hidden behind a 'advanced' button which, when pressed, would display all settings?

**Comment by willemarcel** [comment]
@DaveF63 It's a good suggestion! We will take it into consideration during the planning of the new interface.

**Comment by willemarcel** [comment]
With the release of the new version, this issue is solved.
