### ISSUE TITLE
Show changesets of new users

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#67]
From a recent talk thread on responding to vandalism [[1]](https://lists.openstreetmap.org/pipermail/talk/2017-March/077678.html) [[2]](https://lists.openstreetmap.org/pipermail/talk/2017-March/077690.html):

> Users who have invested into a number of Openstreetmap contributions seldom spend their karma into vandalism, so my experience is that patrolling contributions by new users catches most deliberate mayhem.

The default filter is to show suspicious changesets. An option to show only changesets of new users will be useful for the community to review.

<img width="391" alt="screenshot 2017-03-20 13 56 12" src="https://cloud.githubusercontent.com/assets/126868/24092569/05276b5c-0d75-11e7-931b-4fcba281652a.png">

A list of new users is available from http://resultmaps.neis-one.org/newestosm

**Comment by planemad** [comment]
cc @batpad @willemarcel

**Comment by bkowshik** [comment]
@planemad, after voice with @manoharuss I worked on this PR last week: https://github.com/mapbox/osmcha/pull/9/ which flags the first 5 changesets of a users with a reason `New mapper`. Let me know if that solves this usecase.
