### ISSUE TITLE
Ideas for a map based interface

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#68]
[OpenStreetMap Analytic Difference Engine](https://osm.expandable.dk) ([Code](https://github.com/MichaelVL/osm-analytic-tracker)) has a very verbose but practically useful interface for reviewers to see the details of many edits at once.

<img width="1221" alt="screenshot 2017-03-20 14 05 23" src="https://cloud.githubusercontent.com/assets/126868/24092771/62cd17d8-0d76-11e7-9365-ccc81cf7255d.png">

**Advantages**
- Quickly helps see a details of the tags of features contributed in the changeset
- Brows through multiple changesets in a very short time, avoiding the load times of opening individual changesets

**Comment by willemarcel** [comment]
Solved with the new interface!
