### ISSUE TITLE
Add a filter to ChangesetListView

### ISSUE THREAD

**Issue by willemarcel** [willemarcel/osmcha-django#7]
- [ ] Implement filters to ChangesetListView, we can use django-filter to it
- [ ] Filters by id, harmfull, is_suspect, checked, editor fields

**Comment by alexandre-mbm** [comment]
See tip regarding coding of issue in #6.

**Comment by batpad** [comment]
Would also be useful to have a filter for "suspicious reason".

Is someone working on this @willemarcel ? I'm happy to look into this if not. I have used `django-filter` before and this might be quite straightforward (at least the back-end - the front-end maybe a little more complex).

**Comment by willemarcel** [comment]
hi, @batpad 

I wrote a similar filter in another application, so I think it's faster if I solve it.
