### ISSUE TITLE
Improve user documentation

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#70]
The osmcha UI is really powerful and allows for a high degree of freedom to filter a list of changesets. There is however a lack of any documentation or tutorial that allows the larger mapping community to use this tool effectively. What we need:

- A beginner tutorial on using osmcha to review local changesets on https://www.openstreetmap.org/diary
- A documentation of the features of osmcha and UI on https://wiki.openstreetmap.org/wiki/OSMCHA

cc @manoharuss

**Comment by willemarcel** [comment]
@planemad very good suggestion! It really lacks documentation about how to use `osmcha`.

As we are rebuilding the interface and will have a lot of changes, I'm not sure if it's worth to spend time on documentation now.

**Comment by willemarcel** [comment]
I believe it was fixed with the https://osmcha.mapbox.com/api-docs/ and https://osmcha.mapbox.com/about
