### ISSUE TITLE
Find other edits by user

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#76]
The usual action to inspect a new or suspicious user is to inspect other changes by the same user to find any further edits that need fixing https://osmcha.mapbox.com/47173090

Currently this involves going to the osmcha homepage, manually typing the username and make sure to change the filters to `show all`. This should rather be a single step process from any changeset page. Maybe a small magnifying glass next to the username can provide such a link.

**Comment by willemarcel** [comment]
Opened the issue on `osmcha-frontend`
