### ISSUE TITLE
Findother edits in the area

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#77]
Similiar to https://github.com/willemarcel/osmcha-django/issues/76 , it would be good to search for other recent changesets in the vicinity of the one that is being inspected. This helps spot any outbreak of bad edits easily and understand how actively edited the map location is.

**Comment by willemarcel** [comment]
@planemad Could you reopen this ticket in https://github.com/mapbox/osmcha-frontend/ if you think it is yet relevant?
