### ISSUE TITLE
Indicate valid/invalid stats for a user on the changeset page

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#78]
While reviewing a changeset, it is extremely helpful to know how many of the users previous changesets have been validated/invalidated. This gives better context of how experienced the user is and helps the reviewer dig deeper on users who are known to make mistakes.

**Comment by willemarcel** [comment]
@planemad Now that the API offers an endpoint with the information you want, I'm closing this issue and we can continue discussing it on https://github.com/mapbox/osmcha-frontend/issues/114
