### ISSUE TITLE
HTTP 500 during login to osmcha

### ISSUE THREAD

**Issue by bkowshik** [willemarcel/osmcha-django#79]
![osmcha-login](https://cloud.githubusercontent.com/assets/2899501/24351679/4ed5be36-1304-11e7-8d50-d4de1ec79e61.gif)

---

cc: @willemarcel

**Comment by batpad** [comment]
This is not a problem with the osmcha code. This is a problem of the deploy that allows `http` access, but the login only works with `https`. Use `https` and the login will work, and we should fix the issue with the deploy soon.
