### ISSUE TITLE
Usernames with spaces aren't handled correctly

### ISSUE THREAD

**Issue by alantrick** [willemarcel/osmcha-django#84]
Spaces in usernames appear to be removed, and so 1) they look funny and 2) generate incorrect links to OSM user pages.

**Comment by willemarcel** [comment]
@alantrick Do you have some case for this? I have never seen any error caused by spaces in the usernames...

**Comment by alantrick** [comment]
It doesn't always do it, but here is an example: https://osmcha.mapbox.com/47644769/

Note that BC Hiker's username has a space in it, but the one in Alan Trick's username is missing.

**Comment by willemarcel** [comment]
@alantrick Have you changed your username sometime to add the space?

**Comment by alantrick** [comment]
I don't think so.

**Comment by willemarcel** [comment]
I discovered that django is storing the usernames without spaces. I'll see a way to fix it. Thank you very much for the report!

**Comment by willemarcel** [comment]
Solved!

**Comment by batpad** [comment]
Just a note @alantrick that this is not deployed on https://osmcha.mapbox.com yet - will update here when the fix has been deployed so you can confirm. Thank you again for the report.
