### ISSUE TITLE
Filter by changeset source

### ISSUE THREAD

**Issue by dalkvist** [willemarcel/osmcha-django#87]
Is it possible to make the changeset source field filterable?
We are having some small issues in Sweden with people using data sources that are promoted as open data but are basically under cc-by-nc so not compatible with the odbl.

**Comment by willemarcel** [comment]
Hi @dalkvist !
The source filter field is not on the frontend, but you can already filter changeset by source. Use the parameter `source__icontains`, for example: https://osmcha.mapbox.com/?source__icontains=IBGE

**Comment by dalkvist** [comment]
Ah, thanks!
