### ISSUE TITLE
Getting content type as JSON

### ISSUE THREAD

**Issue by kepta** [willemarcel/osmcha-django#89]
The current api for eg. `https://osmcha-django-api-test.tilestream.net/api/v1/changesets?page=10&page_size=30`, returns
``` csv
content-type:text/html; charset=utf-8
```
Can we make that a JSON response ?

cc @willemarcel  @batpad

**Comment by willemarcel** [comment]
@kepta Yes, just add `format=json` to the urls param, to changeset and feature list endpoints we also have the `format=csv` option.
