### ISSUE TITLE
`CHANGESETS_FILTER` setting

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#9]
The `CHANGESETS_FILTER` setting is required to be defined when importing changesets, but there is no default value specified in settings. Can we set a default in `config/settings/common.py` like `CHANGESETS_FILTER = None` ?

**Comment by willemarcel** [comment]
This variable needs to point to a geojson file containing a polygon with the area you want to filter the changesets to be imported. If you want to import all the world, you can set it as None. 

Thanks for the report, I will configure it better soon.

**Comment by batpad** [comment]
Ah my bad, @willemarcel did not realize the purpose of this setting. This seems very useful. I think adding a note about it in the README should be enough to close?

**Comment by willemarcel** [comment]
I'm with some ideas of a better way to define it as None by default. I'll work on this soon.

**Comment by willemarcel** [comment]
Hi, @batpad 

I defined CHANGESETS_FILTER as None in common.py, added  `env('DJANGO_CHANGESETS_FILTER', None)` to production.py and finally added information about this in the README.

https://github.com/willemarcel/osmcha-django/commit/59bc31336e735dbbcb86de5e528415edba754357
