### ISSUE TITLE
[api] Return tagged features in changeset end-point

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#90]
It would be nice to get the list of suspicious  / tagged features that are part of this changeset when requesting data about a particular changeset.

cc @willemarcel @kepta

**Comment by willemarcel** [comment]
@batpad Good catch. Last week I was thinking about to have an endpoint to return the features that match an Area of Interest. What do you think about? I just need to check if it's possible to use the same filter fields we use to get the changesets or if it's necessary to change something to deal with the features.

**Comment by willemarcel** [comment]
@batpad @kepta It is already implemented. Inside the properties of a changeset, we have a `features` field that list its features.
