### ISSUE TITLE
All edits from latest iD getting flagged as suspicious

### ISSUE THREAD

**Issue by planemad** [willemarcel/osmcha-django#91]
After the release of iD 2.2, all edits are now flagged as suspicious with `Unknown iD instance`

**Comment by ImreSamu** [comment]
as I see  the iD Editor  changeset  `host` value changed 
* from  `https://www.openstreetmap.org/id` 
*  to  `http://www.openstreetmap.org/edit`

see ( https://github.com/openstreetmap/iD/issues/3950 )
```xml
<changeset id="48642775" created_at="2017-05-13T08:33:46Z" closed_at="2017-05-13T08:33:47Z" open="false" user="ajithkarunaratne" uid="2266634" min_lat="7.0379759" min_lon="79.9113648" max_lat="7.0381690" max_lon="79.9114223" comments_count="0">
  <tag k="comment" v="Corrections Based on new Digital Globe Imabe"/>
  <tag k="locale" v="en-US"/>
  <tag k="host" v="https://www.openstreetmap.org/edit"/>
  <tag k="imagery_used" v="Bing aerial imagery"/>
  <tag k="created_by" v="iD 2.2.1"/>
</changeset>
```

And it has been fixed  3 days ago:  https://github.com/willemarcel/osmcha/commit/68a834e7bfd08cd5afdb4bafd00da476c1ed0e31 in the code.
But I don't know wich version is running on the http://osmcha.mapbox.com

**Comment by batpad** [comment]
This is fixed on master. Sorry, this is a delay on my end deploying to production.

**Comment by batpad** [comment]
This is fixed on master. Sorry, this is a delay on my end deploying to production.

**Comment by batpad** [comment]
This is fixed on master. Sorry, this is a delay on my end deploying to production.

**Comment by batpad** [comment]
Oops, sorry for the multiple messages. This is what I get for trying to use github on my phone :(

**Comment by batpad** [comment]
Deployed. Sorry about that blip.
