### ISSUE TITLE
profanity tag

### ISSUE THREAD

**Issue by grinapo** [willemarcel/osmcha-django#93]
What's triggering the profanity tag feature here?
https://osmcha.mapbox.com/48444553/features/way-491732441/

**Comment by willemarcel** [comment]
@grinapo The features analysis is made by https://github.com/mapbox/osm-compare that uses https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/ to add the profanity suspicion reason. I tried and didn't identify any naughty word in the feature...

**Comment by ImreSamu** [comment]
>I tried and didn't identify any naughty word in the feature...

the [2. word](https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/search?utf8=%E2%9C%93&q=P%C3%A9ter&type=)  is in the (fr=French dictionary)

**Comment by willemarcel** [comment]
Thanks, @ImreSamu

**Comment by grinapo** [comment]
OMFG my name is a dirty word!
