### ISSUE TITLE
[privacy] remove requests to external resources

### ISSUE THREAD

**Issue by tetraf** [willemarcel/osmcha-django#94]
For privacy concerns it may be good to remove all references to following domains and to distribute js and css locally with OSMChA:
* ajax.googleapis.com (jquery)
* cdnjs.cloudflare.com (moment)
* netdna.bootstrapcdn.com (bootstrap)
* unpkg.com (some css)

**Comment by willemarcel** [comment]
The interface is update and doesn't use those CDNs anymore.
