### ISSUE TITLE
Filter map doesn't display

### ISSUE THREAD

**Issue by RafalR** [willemarcel/osmcha-django#96]
Filter bbox map doesn't display

![image](https://user-images.githubusercontent.com/659513/27013146-a4da11a4-4ede-11e7-8e6a-e184e335d635.png)

**Comment by willemarcel** [comment]
@RafalR strange... Could you open your browser console and check if there are some error message? Assure you are accessing the https://osmcha.mapbox.com/ with `https`

**Comment by RafalR** [comment]
Similar problems have occurred in other sites. It is possible that the latest version of Mapbox maps api this problem does not occur

- https://github.com/mapillary/mapillary_issues/issues/2260
- https://github.com/mapbox/mapbox-gl-js/issues/3143

Firefox
![obraz](https://user-images.githubusercontent.com/659513/27029743-e6b83c82-4f69-11e7-8407-d76d4c3777f4.png)
Chrome
![obraz](https://user-images.githubusercontent.com/659513/27029810-269be286-4f6a-11e7-81e5-32eaafa4f0d5.png)
