### ISSUE TITLE
Allow to filter for changesets that have suspicious features

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#97]
Probably need to think this through a bit, but can possibly useful for a few different cases. Esp. to look through a reason that applies to changesets, but then drill down / prioritize only changesets which contain features that have been flagged for some reason by feature level functions.

cc @abhisheksaika @willemarcel @rasagy @kepta

**Comment by willemarcel** [comment]
It's solved with https://github.com/willemarcel/osmcha-django/pull/127
