### ISSUE TITLE
Can't log in with osm profile

### ISSUE THREAD

**Issue by diegodeg58** [willemarcel/osmcha-django#98]
Basicly I can't get log in with my profile of OSM in web http://osmcha.mapbox.com/
It shows me "Ooops!!! 500 Looks like something went wrong!"
Can you help me with this thing?  Thanks for the support and thanks for the great tool as is osmcha!

**Comment by willemarcel** [comment]
Hi @diegodeg58 

Sorry, we're having an issue with https redirection, please use always https://osmcha.mapbox.com/ (with http**s**).

**Comment by diegodeg58** [comment]
That's it! Thanks for the support! :+1:
